/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues_app;

/**
 *
 * @author ARNAUD
 */
public class change_password extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public change_password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        user_name_label = new javax.swing.JLabel();
        icon_login = new javax.swing.JLabel();
        pass_label1 = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        btn_connecter = new javax.swing.JButton();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        password3 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(998, 635));
        setMinimumSize(new java.awt.Dimension(998, 635));
        setPreferredSize(new java.awt.Dimension(998, 635));
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        bg.setMaximumSize(new java.awt.Dimension(998, 635));
        bg.setMinimumSize(new java.awt.Dimension(998, 635));
        bg.setPreferredSize(new java.awt.Dimension(998, 635));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name_label.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        user_name_label.setForeground(new java.awt.Color(255, 153, 0));
        user_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_name_label.setText("Ancien mot de pass");
        bg.add(user_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 230, -1));
        bg.add(icon_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 128, 128));

        pass_label1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        pass_label1.setForeground(new java.awt.Color(255, 153, 0));
        pass_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_label1.setText("repeter le nouveau mot de pass");
        bg.add(pass_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 330, 40));

        pass_label.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        pass_label.setForeground(new java.awt.Color(255, 153, 0));
        pass_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_label.setText("nouveau mot de pass");
        bg.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 240, 20));

        btn_connecter.setBackground(new java.awt.Color(0, 153, 153));
        btn_connecter.setForeground(new java.awt.Color(255, 255, 255));
        btn_connecter.setText("CHANGER");
        btn_connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connecterActionPerformed(evt);
            }
        });
        bg.add(btn_connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 170, 40));

        password1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 470, 30));

        password2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 470, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("indice de recuperation");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 270, -1));

        password3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        password3.setForeground(new java.awt.Color(255, 51, 0));
        bg.add(password3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 470, 30));
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 470, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connecterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_connecterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_connecter;
    private javax.swing.JLabel icon_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel pass_label1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JPasswordField password3;
    private javax.swing.JLabel user_name_label;
    // End of variables declaration//GEN-END:variables
}
