/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues_app;


import Dao.Info_utilisateur_courant;
import Utilisateurs.Libraire;
import gestion.de.librairie.Connecxion_a_DB;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ARNAUD
 */

public class login extends javax.swing.JFrame {
Statement stmt;
  Info_utilisateur_courant session=new Info_utilisateur_courant();
Libraire librqire=new Libraire();
Connecxion_a_DB myconnect=new Connecxion_a_DB();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        //centrer le jframe
        this.setLocationRelativeTo(this);
        //panel_login.setVisible(false);
            //jPanel1.setBackground(new Color(2,2,0,100));
        panel_login.setBackground(new Color(2,2,0,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panel_login = new javax.swing.JPanel();
        icon_login = new javax.swing.JLabel();
        user_name_label = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        pass_label = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btn_connecter = new javax.swing.JButton();
        btn_pass_oublier = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_info = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 470));
        setResizable(false);

        bg.setMaximumSize(new java.awt.Dimension(690, 470));
        bg.setMinimumSize(new java.awt.Dimension(690, 470));
        bg.setPreferredSize(new java.awt.Dimension(690, 470));
        bg.setLayout(null);

        panel_login.setBackground(new java.awt.Color(255, 0, 255));
        panel_login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Authentifcation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panel_login.setMaximumSize(new java.awt.Dimension(690, 470));
        panel_login.setPreferredSize(new java.awt.Dimension(690, 470));

        icon_login.setForeground(new java.awt.Color(255, 255, 255));
        icon_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sprite0.png"))); // NOI18N

        user_name_label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        user_name_label.setForeground(new java.awt.Color(255, 255, 255));
        user_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_name_label.setLabelFor(user_name);
        user_name_label.setText("NOM UTILISATEUR");

        user_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });

        pass_label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        pass_label.setForeground(new java.awt.Color(255, 255, 255));
        pass_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_label.setLabelFor(password);
        pass_label.setText("MOT DE PASSE");

        password.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 51, 0));

        btn_connecter.setBackground(new java.awt.Color(0, 153, 153));
        btn_connecter.setForeground(new java.awt.Color(255, 255, 255));
        btn_connecter.setText("CONNECTER");
        btn_connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connecterActionPerformed(evt);
            }
        });

        btn_pass_oublier.setBackground(new java.awt.Color(0, 153, 153));
        btn_pass_oublier.setForeground(new java.awt.Color(255, 255, 255));
        btn_pass_oublier.setText("Récuperer mon passe");
        btn_pass_oublier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pass_oublierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_login)
                .addGap(210, 210, 210))
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_loginLayout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(user_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_loginLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_loginLayout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel_loginLayout.createSequentialGroup()
                            .addComponent(btn_connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pass_oublier, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_login, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pass_oublier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_connecter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(panel_login);
        panel_login.setBounds(220, 20, 560, 520);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        txt_info.setBackground(new java.awt.Color(255, 255, 255));
        txt_info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_info.setForeground(new java.awt.Color(255, 0, 51));
        txt_info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_info.setText("<html>si vous avez oublier voutre passe rempileir uniquement le champs \"nom utilisateur\" <br>puis clicer sur \"recuperer mon passe\"</html>");
        txt_info.setToolTipText("");
        txt_info.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txt_info.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        txt_info.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_info, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txt_info, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel1);
        jPanel1.setBounds(220, 540, 560, 90);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BON BG.jpg"))); // NOI18N
        bg.add(jLabel1);
        jLabel1.setBounds(-6, -6, 940, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connecterActionPerformed
        if(!user_name.getText().equals("") && !password.getText().equals("")){
          librqire=librqire.login(user_name.getText(), password.getText());
          //si la connection a reussir 
          if(!librqire.user_name().equals("")){
              //recupere les parametre du compte
              session.courent_user=librqire;
              this.setVisible(false);
              new Home().setVisible(true); 
          }

        }else{
             JOptionPane.showMessageDialog(null,"Vous devez remplir les deux champs");
        }
     
    }//GEN-LAST:event_btn_connecterActionPerformed

    private void btn_pass_oublierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pass_oublierActionPerformed
if(!user_name.getText().equals("")){
           String indice =librqire.get_indice_password(user_name.getText());
       if(!indice.equals("")){
           txt_info.setText(indice);
       }
}else{
    JOptionPane.showMessageDialog(null,"enter minimum votre user name");
}
    }//GEN-LAST:event_btn_pass_oublierActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_connecter;
    private javax.swing.JButton btn_pass_oublier;
    private javax.swing.JLabel icon_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_login;
    private javax.swing.JLabel pass_label;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel txt_info;
    private javax.swing.JTextField user_name;
    private javax.swing.JLabel user_name_label;
    // End of variables declaration//GEN-END:variables
}
